routes/web.php
    Route::resource('agreements', 'AgreementController');       
    // route bank-accounts
    Route::resource('bank-accounts', 'BankAccountController');            
    // route static-pages
    Route::resource('static-pages', 'StaticPageController')->except(['create' , 'show']); 
    // route contacts
    Route::resource('contacts', 'ContactController')->except(['create' , 'show']); 
    Route::get('contact/reply', 'ContactController@reply')->name('contact.reply'); 
    // route settings
    Route::resource('settings', 'SettingController')->except(['index' , 'show']);                
    // route logout
    Route::get('logout', 'DashboardController@logout')->name('logout');

}); // end of route prefix dashboard
//##################################  END: route group dashboard ########################################


///////////////////////////////////////  BEGIN: route group web ////////////////////////////////////////

Route::name('web.')->namespace('Web')->group(function(){

    // route get categories
    Route::get('/' , 'CategoryController@category')->name('category');
    // route home
    Route::get('home/{slug}' , 'HomeController@home')->name('home');
    Route::get('pagination' , 'HomeController@pagination')->name('pagination');

    
    ################################################## BEGIN: authentication #########################################
    // route register
    Route::get('register' , 'AuthenticationController@register')->name('register');
    // route register store
    Route::post('register/store' , 'AuthenticationController@registerStore')->name('register.store');
    // route login
    Route::get('login' , 'AuthenticationController@login')->name('login');
    // route login auth
    Route::post('login/auth' , 'AuthenticationController@loginAuth')->name('login.auth');
    
    ################################################## END: authentication #########################################
    

    ################################################## END: statics #########################################

    // route agreement
    Route::get('static/{key}' , 'StaticPageController@static')->name('static');
    // route about
    Route::get('about' , 'StaticPageController@about')->name('about');
    // route commission
    Route::get('commission' , 'StaticPageController@commission')->name('commission');
    // route contact
    Route::get('contact' , 'StaticPageController@contact')->name('contact');
    // route store contact
    Route::post('store/contact' , 'StaticPageController@store')->name('store.contact');
    // route payment 
    Route::get('payment/{slug}' , 'PaymentController@payment')->name('payment');
    // route web payment now 
    Route::post('payment/now' , 'PaymentController@paymentNow')->name('payment.now');

    ################################################## BEGIN: statics #########################################


    ################################################## BEGIN: active account #########################################
    // route verfiy
    Route::get('verfiy/{slug}' , 'AuthenticationController@verfiy')->name('verfiy');
    // route resend code
    Route::get('resend/code/{slug}' , 'AuthenticationController@resendCode')->name('resend.code');
    // route active phone
    Route::post('active/phone' , 'AuthenticationController@activePhone')->name('active.phone');

    ################################################## END: active account #########################################

    ################################################## BEGIN: reset password #########################################
    // route forget password
    Route::get('forget/password' , 'AuthenticationController@forgetPassword')->name('forget.password');
    // route send code reset password
    Route::post('send/code/reset/password' , 'AuthenticationController@sendCodeResetPassword')->name('send.code.reset.password');
    // route verfiy code reset password
    Route::get('verfiy/code/reset/password/{slug}' , 'AuthenticationController@verfiySendCodeResetPassword')->name('verfiy.code.reset.password');
    // route reset password
    Route::post('active/code/reset/password' , 'AuthenticationController@activeSendCodeResetPassword')->name('active.code.reset.password');
    // route reset password
    Route::get('reset/password/{slug}' , 'AuthenticationController@resetPassword')->name('reset.password');  
    // route reset password
    Route::post('new/password' , 'AuthenticationController@newPassword')->name('new.password');
    
    ################################################## END: reset password #########################################
    

    ################################################## BEGIN: products #########################################
    // route single product
    Route::get('product/{slug}' , 'ProductController@getProduct')->name('product');  
    
    ################################################## END: products ###########################################
    

    ################################################## BEGIN: opposed #########################################
    
    // route opposeds
    Route::get('opposeds' , 'OpposedController@getAllOpposed')->name('opposeds');  
    // route opposed
    Route::get('opposed/{slug}' , 'OpposedController@getOpposed')->name('opposed');  
    
    
    ################################################## END: opposed ###########################################
    
    
    ################################################## BEGIN: opposed #########################################
    
    // route search
    Route::get('public/search' , 'SearchController@searchPublic')->name('public.search');  

    // route search
    Route::post('search' , 'SearchController@searchSimple')->name('search');  
    
    // route search
    Route::get('search/advanced' , 'SearchController@searchAdvanced')->name('search.advanced');  
    
    // route map
    Route::get('search/map' , 'SearchController@searchMap')->name('search.map');  
     
    // route search
    Route::post('search/advanced/store' , 'SearchController@searchAdvancedStore')->name('search.advanced.store'); 

    // route get attribute
    Route::get('get/attribute/search' , 'SearchController@getAttributeSearch')->name('get.attribute.search');

    ################################################## END: opposed ###########################################

    // route get option other addition
    Route::get('get/other/addition' , 'SearchController@getOtherAddition')->name('get.other.addition');


    Route::middleware('website')->group(function(){
        
        // route logout
        Route::get('logout' , 'AuthenticationController@logout')->name('logout');
        // route profile
        Route::get('profile' , 'ProfileController@profile')->name('profile');
        // route edit profile
        Route::get('edit/profile' , 'ProfileController@edit')->name('edit.profile');
        // route update profile
        Route::put('update/profile' , 'ProfileController@update')->name('update.profile');
        // route upload image
        Route::post('upload/image' , 'ProfileController@uploadImage')->name('upload.image');
        // route add to favorite
        Route::get('add/to/favorite' , 'HomeController@addToFavorite')->name('add.to.favorite');
        // route get favorite
        Route::get('profile/favorite' , 'ProfileController@getFavorite')->name('profile.favorite');
        // route my product
        Route::get('profile/product' , 'ProfileController@myProduct')->name('profile.product');
        // route done sale
        Route::get('done/sale' , 'ProfileController@doneSale')->name('done.sale');
        
        ################################################## BEGIN: add new product ###########################################
        
        // route add product
        Route::get('add/product' , 'ProductController@addProduct')->name('add.product');
        // route edit product
        Route::get('edit/product/{slug}' , 'ProductController@editProduct')->name('edit.product');
        // route add product
        Route::put('update/product' , 'ProductController@updateProduct')->name('update.product');
        // route delete product
        Route::get('delete/product' , 'ProductController@deleteProduct')->name('delete.product');
        // route delete image
        Route::get('delete/image' , 'ProductController@deleteImage')->name('delete.image');
        // route get addition
        Route::get('get/addition' , 'ProductController@getAddition')->name('get.addition');
        // route get attribute
        Route::get('get/attribute' , 'ProductController@getAttribute')->name('get.attribute');
        // route get direction
        Route::get('get/direction' , 'ProductController@getDirection')->name('get.direction');
        // route get option other addition
        Route::get('get/option/other/addition' , 'ProductController@getOptionOtherAddition')->name('get.option.other.addition');
        // route store product
        Route::post('store/product' , 'ProductController@storeProduct')->name('store.product');
        // route report product
        Route::post('report/product' , 'ProductController@reportProduct')->name('report.product');
        
        ################################################## END: add new product ###########################################
        
        ################################################## END: add new product ###########################################
        
        // route chat 
        Route::get('chat/{slug}' , 'ChatController@chat')->name('chat');
        // route chat 
        Route::post('uploade/file/chat' , 'ChatController@uploadFile')->name('uploade.file.chat');

        ################################################## END: add new product ###########################################

    });

});

app/Http/Controllers/Web/ProfileController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Requests\Web\RegisterRequest;
use App\Repositories\AuthenticationRepositoryInterface;
use App\Repositories\CityRepositoryInterface;
use App\Repositories\ProductRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use phpDocumentor\Reflection\Types\This;

class ProfileController extends Controller
{

    public $authenticationrepository;
    public $cityrepository;
    public $productrepository;

    public function __construct(AuthenticationRepositoryInterface $authenticationrepository,
                                CityRepositoryInterface $cityrepository,
                                ProductRepositoryInterface $productrepository
    )
    {
        $this->authenticationrepository = $authenticationrepository;
        $this->cityrepository           = $cityrepository;
        $this->productrepository        = $productrepository;
    } // end of construct

    public function profile()
    {

        return view('website.profile.profile');

    } // end of category
    
    public function edit()
    {

        $cities = $this->cityrepository->getAll();

        return view('website.profile.profile' , compact('cities'));

    } // end of category

    public function update(RegisterRequest $request)
    {

        if (auth()->user()->type_id == 1) {

            $attribute = $request->except(

                    'commercial_register' ,
                    'tax_number' ,
                    'password' ,
                    'confirm_password',
                    'name_bank',
                    'name_account_bank',
                    'number_account_bank',
                    'number_eban_bank',
                    'company_name'
                    
            );

            $attribute['first_name']  = $request->first_name;


        } else  
        {

            $attribute = $request->except(

                    'password' ,
                    'confirm_password' ,
                    'second_name' ,
                    'last_name',
                    'first_name'

            );
            
            $attribute['first_name']  = $request->company_name;
            
        } // end of else if auth user

        if($request->password) 
        {

            $attribute['password']  = bcrypt($request->password);

        }

        auth()->user()->update($attribute);

        session()->put('edit-user' , true);

        return redirect()->route('web.profile')->with('success' , 'تم تحديث البيانات بنجاح');

    } // end of update

    public function uploadImage(Request $request)
    {

        // uploade file image
        if ($request->hasFile('image')) {
        
            // Delete old internal_image
            Storage::delete(auth()->user()->id);

            // Upload new internal_image
            $attribute['image'] = $request->file('image')->store('user');

        } // end of if image

        auth()->user()->update($attribute);            

        return response()->json([

            'image'   => url('storage/' . auth()->user()->image),
            'user_id' => auth()->user()->id,
            
        ]);

    } // end of upload image

    public function getFavorite()
    {
        return view('website.profile.profile');
    }

    public function myProduct()
    {
        
        $products = auth()->user()->products()->paginate(1);



        return view('website.profile.profile' , compact('products'));

    } // end of my product

    public function doneSale(Request $request)
    {

        $product = $this->productrepository->findOne($request->id);

        $product->update(['status' => 'تم البيع' , 'date_sale' => now()]);

        return response()->json();

    } // end of done sale

} // end of class

resources/views/website/profile/data_person.blade.php
<div class="profile-main-grid col-lg-9 col-md-8">
    <!--start profile-main-grid-->
    <div class="main-profile-div sm-raduis gray-bg">
        <h2 class="circle-item second_color">البيانات الشخصية : 

            <a href="{{ route('web.edit.profile') }}" class="simple-btn open-edit-form"><i class="fa fa-edit"></i></a>
            
        </h2>


        <div class="row">

            <!--start div-->
            <div class="col-12 profile-data">
                <form class="row profile-form orange-form" action="{{ route('web.update.profile' , auth()->user()->id) }}" method="post">
                    @csrf
                    @method('PUT')

                    @if(auth()->user()->type_id == 1)

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color">الاسم الأول</label>
                                <input type="text" class="form-control" name="first_name" value="{{ auth()->user()->first_name }}" disabled>
                            </div>
                        </div>

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color">الاسم الثاني</label>
                                <input type="text" class="form-control" name="second_name" value="{{ auth()->user()->second_name }}" disabled>
                            </div>
                        </div>

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color">اسم العائلة</label>
                                <input type="text" class="form-control" name="last_name" value="{{ auth()->user()->last_name }}" disabled>
                            </div>
                        </div>

                    @else

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color">اسم المؤسسة</label>
                                <input type="text" name="compnay_name" class="form-control"
                                    value="{{ auth()->user()->first_name }}" disabled>
                            </div>
                        </div>

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color">السجل التجاري</label>
                                <input type="number" class="form-control" name="commercial_register" value="{{ auth()->user()->commercial_register }}" disabled>
                            </div>
                        </div>

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color">الرقم الضريبي</label>
                                <input type="number" class="form-control" name="tax_number" value="{{ auth()->user()->tax_number }}" disabled>
                            </div>
                        </div> 

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color">اسم البنك</label>
                                <input type="text" class="form-control" name="name_bank" value="{{ auth()->user()->name_bank }}" disabled>
                            </div>
                        </div>                                    

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color"> اسم الحساب </label>
                                <input type="text" class="form-control" name="name_account_bank" value="{{ auth()->user()->name_account_bank }}" disabled>
                            </div>
                        </div>                                    

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color"> رقم الحساب </label>
                                <input type="text" class="form-control" name="number_account_bank" value="{{ auth()->user()->number_account_bank }}" disabled>
                            </div>
                        </div>     

                        <div class="col-12" data-aos="fade-in">
                            <div class="form-group">
                                <label class="moving-label second_color"> رقم الايبان </label>
                                <input type="text" class="form-control" name="number_eban_bank" value="{{ auth()->user()->number_eban_bank }}" disabled>
                            </div>
                        </div>                                    

                    @endif

                    <div class="col-12" data-aos="fade-in">
                        <div class="form-group">
                            <label class="moving-label second_color"> المدينة</label>
                            <input type="tel" class="form-control" name="phone" value="{{ auth()->user()->city->name }}"
                                minlength="11" maxlength="14" disabled>
                        </div>
                    </div>

                    <div class="col-12" data-aos="fade-in">
                        <div class="form-group">
                            <label class="moving-label second_color">رقم الجوال</label>
                            <input type="tel" class="form-control" name="phone" value="{{ auth()->user()->phone }}"
                                minlength="11" maxlength="14" disabled>
                        </div>
                    </div>

                    
                    <div class="col-12" data-aos="fade-in">
                        <div class="form-group">
                            <label class="moving-label second_color">البريد الإلكتروني</label>
                            <input type="email" class="form-control" name="email" value="{{ auth()->user()->email }}"
                                disabled>
                        </div>
                    </div>

                    {{--<div class="col-12" data-aos="fade-in">
                        <div class="form-group">
                            <label class="moving-label second_color">كلمة المرور</label>
                            <input type="password" class="form-control" id="password"
                                value="" disabled>
                        </div>
                    </div>


                    <div class="col-12" data-aos="fade-in">
                        <div class="form-group">
                            <label class="moving-label second_color">تأكيد كلمة المرور</label>
                            <input type="password" class="form-control" name="password_confirm"
                                value="" disabled>
                        </div>
                    </div>--}}

                    <div class="col-lg-12 text-center hide-element">
                        <div class="form-group">
                            <button type="submit" class="border-btn"><span>حفظ </span></button>
                        </div>
                    </div>


                </form>
            </div>
            <!--end div-->
        </div>
    </div>
</div>

resources/views/website/profile/profile.blade.php
@extends('website.layouts.app')

@if(\Request::route()->getName() == 'web.profile')

    @section('title' , 'حسابي')

@elseif(\Request::route()->getName() == 'web.edit.profile')

    @section('title' , 'تعديل البيانات الشخصية')

@elseif(\Request::route()->getName() == 'web.profile.favorite')

    @section('title' , 'المفضلة')

@elseif(\Request::route()->getName() == 'web.profile.product')

    @section('title' , 'أعلاناتي')

@endif

@push('css')



@endpush
@section('content')
<!-- start pages-header
 ================ -->
<section class="pages-header text-center">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12">
                <div class="page-header-content" data-aos="zoom-out">
                    <h2 class="white-text">حسابي</h2>
                    <div class="breadcrumbes second_color">
                        <a href="{{ route('web.home' , session('categorySlug')) }}"><i class="fa fa-home"></i>الرئيسية</a>
                        
                            @if(\Request::route()->getName() == 'web.profile')

                                البيانات الشخصية

                            @elseif(\Request::route()->getName() == 'web.edit.profile')

                                تعديل البيانات الشخصية

                            @elseif(\Request::route()->getName() == 'web.profile.favorite')

                                المفضلة

                            @elseif(\Request::route()->getName() == 'web.profile.product')

                               أعلاناتي 

                            @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--end pages-header-->


<!-- start profile-pg
 ================ -->
<section class="profile-pg margin-div" data-aos="fade-in">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h3 class="shadow-title first_color">حسابي </h3>
            </div>
        </div>


        <div class="profile-content">
            <div class="row">
                <!--start profile-list-grid-->
                <div class="profile-list-grid col-lg-3 col-md-4">
                    <!--start div-->
                    <div class="profile-img text-center first_color sm-raduis" data-aos="fade-in">
                        <form action="">
                            <div class="avatar-upload">
                                <div class="avatar-edit">
                                    <input type="file" id="imageUpload" data-url="{{ route('web.upload.image') }}" class="hidden-input"
                                        accept=".png, .jpg, .jpeg">
                                    <label for="imageUpload"></label>
                                </div>
                                <div class="avatar-preview">
                                    <div id="imagePreview"
                                        style="background-image: url({{ url('storage/' . auth()->user()->image) }});">
                                    </div>
                                </div>
                            </div>
                        </form>
                        <h3 class="second_color">{{ auth()->user()->first_name }} {{ auth()->user()->second_name }} {{ auth()->user()->last_name }}</h3>

                        {{ auth()->user()->email }}

                    </div>
                    <!--end div-->

                    <!--start div-->
                    <div class="profile-list-grid" data-aos="fade-in">
                        <div class="profile-list has_seudo gray-bg">
                            <ul class="list-unstyled">
                                <li class="{{ areActiveRoutes(['web.profile']) }}">
                                    <a href="{{ route('web.profile') }}">
                                        <i class="far fa-user-circle"></i>
                                        البيانات الشخصية
                                    </a>
                                </li>

                                <li class="{{ areActiveRoutes(['web.profile.favorite']) }}">
                                    <a href="{{ route('web.profile.favorite') }}">
                                        <i class="far fa-heart"></i>
                                        المفضلة
                                    </a>
                                </li>

                                <li class="{{ areActiveRoutes(['web.profile.product']) }}">
                                    <a href="{{ route('web.profile.product') }}">
                                        <i class="fa fa-bullhorn"></i>
                                        إعلاناتي
                                    </a>
                                </li>

                                {{--<li>
                                    <a href="{{ route('web.profile') }}">
                                        <i class="fa fa-cog"></i>
                                        الإعدادات
                                    </a>
                                </li>--}}

                                <li>
                                    <a href="" id="logout-user" data-redirectlogout="{{ route('web.logout') }}">
                                        <i class="fa fa-power-off"></i>
                                        تسجيل خروج
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!--end div-->
                </div>
                <!--end profile-list-grid-->

                <!-- data person -->
                @if(\Request::route()->getName() == 'web.profile')
                
                    @include('website.profile.data_person')
                
                @endif
                <!-- data person -->
                
                <!-- edit data person -->
                
                @if(\Request::route()->getName() == 'web.edit.profile')
                
                    @include('website.profile.edit')
                
                @endif

                <!-- edit data person -->
                
                <!-- favorite -->
                
                @if(\Request::route()->getName() == 'web.profile.favorite')
                
                    @include('website.profile.favorite')
                
                @endif

                <!-- favorite -->

                <!-- myproduct -->
                
                @if(\Request::route()->getName() == 'web.profile.product')
                
                    @include('website.profile.myproduct')
                
                @endif

                <!-- myproduct -->

            </div>
        </div>

    </div>
</section>
<!--end profile-pg-->

@push('js')

    <script type="text/javascript" src="{{ url('web') }}/back-end/logout.js"></script>
                                        
    @if(session('categoryId') == 1)

        <script type="text/javascript" src="{{ url('web') }}/js/profile.js"></script>
        <script type="text/javascript" src="{{ url('web') }}/back-end/delete-favorite.js"></script>
        <script type="text/javascript" src="{{ url('web') }}/back-end/done-sale.js"></script>
        <script type="text/javascript" src="{{ url('web') }}/back-end/delete-product.js"></script>
        
        @elseif(session('categoryId') == 2)
        
        <script type="text/javascript" src="{{ url('web') }}/back-end/delete-product.js"></script>
        <script type="text/javascript" src="{{ url('web') }}/back-end/done-sale.js"></script>
        <script type="text/javascript" src="{{ url('web') }}/js/profile.js"></script>
        <script type="text/javascript" src="{{ url('web') }}/back-end/delete-favorite.js"></script>
  
    @endif

    @if(session('edit-user') == 'true')


    <script>


        var db = firebase.firestore();

        // Add a new document in collection "users"
        db.collection("users").doc('userId_' + "{{ auth()->user()->id }}").update({
            'name': "{{ auth()->user()->first_name }}" +' '+ "{{ auth()->user()->second_name }}" +' '+ "{{ auth()->user()->last_name }}",
            'email': "{{ auth()->user()->email }}",
            'id': "userId_" + "{{ auth()->user()->id }}",
            'createdAt': firebase.firestore.FieldValue.serverTimestamp(),
            'chattingWith': null,
            'typingTo': null,
            'unReadingCount': 0,
            'status': 'online',
            'slug': "{{ auth()->user()->slug }}",
            'lastSeen': firebase.firestore.FieldValue.serverTimestamp(),
        })
        .then(() => {

            console.log("Document successfully written!");

        })
        .catch((error) => {

            console.error("Error writing document: ", error);
            
        });


    </script>
                        
    @endif

    @php

    session()->forget('edit-user')    

    @endphp    

@endpush

@endsection