routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route group auth
Route::prefix('dashboard')->namespace('Dashboard')->group(function(){

    // route login 
    Route::get('login', 'DashboardController@login')->name('login');
    Route::post('login/auth', 'DashboardController@loginAuth')->name('login.auth');
    Route::get('reset/password', 'DashboardController@resetPassword')->name('reset.password');
    Route::post('send/link', 'DashboardController@sendLink')->name('send.link');
    Route::get('link/reset/password/{code}', 'DashboardController@newPassword')->name('link.reset.password');
    Route::post('update/password', 'DashboardController@updatePassword')->name('update.password');

});

//##################################  BEGIN: route group dashboard ######################################
Route::prefix('dashboard')->middleware('admin')->name('dashboard.')->namespace('Dashboard')->group(function(){

    // route dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');
    // route sliders
    Route::resource('sliders', 'SliderController');      
    // route cities
    Route::resource('cities', 'CityController');    
    // route orders
    Route::resource('orders', 'OrderController');    
    // route sub categories
    Route::resource('categories', 'CategoryController');
    // route products
    Route::resource('products', 'ProductController');
    // route atrributes
    Route::resource('attributes', 'AttributeController');
    Route::get('append/subcategory', 'OptionController@appendSubCategory')->name('append.subcategory');
    // route options
    Route::resource('options', 'OptionController');
    // route price-fillters
    Route::resource('price-fillters', 'PriceFillterController');  
    // route banks
    Route::resource('banks', 'BankController');  
    // route agreements
    Route::resource('agreements', 'AgreementController');       
    // route bank-accounts
    Route::resource('bank-accounts', 'BankAccountController');            
    // route static-pages
    Route::resource('static-pages', 'StaticPageController')->except(['create' , 'show']); 
    // route contacts
    Route::resource('contacts', 'ContactController')->except(['create' , 'show']); 
    Route::get('contact/reply', 'ContactController@reply')->name('contact.reply'); 
    // route settings
    Route::resource('settings', 'SettingController')->except(['index' , 'show']);                
    // route logout
    Route::get('logout', 'DashboardController@logout')->name('logout');

}); // end of route prefix dashboard
//##################################  END: route group dashboard ########################################


///////////////////////////////////////  BEGIN: route group web ////////////////////////////////////////

Route::name('web.')->namespace('Web')->group(function(){

    // route get categories
    Route::get('/' , 'CategoryController@category')->name('category');
    // route home
    Route::get('home/{slug}' , 'HomeController@home')->name('home');
    Route::get('pagination' , 'HomeController@pagination')->name('pagination');

    
    ################################################## BEGIN: authentication #########################################
    // route register
    Route::get('register' , 'AuthenticationController@register')->name('register');
    // route register store
    Route::post('register/store' , 'AuthenticationController@registerStore')->name('register.store');
    // route login
    Route::get('login' , 'AuthenticationController@login')->name('login');
    // route login auth
    Route::post('login/auth' , 'AuthenticationController@loginAuth')->name('login.auth');
    
    ################################################## END: authentication #########################################
    

    ################################################## END: statics #########################################

    // route agreement
    Route::get('static/{key}' , 'StaticPageController@static')->name('static');
    // route about
    Route::get('about' , 'StaticPageController@about')->name('about');
    // route commission
    Route::get('commission' , 'StaticPageController@commission')->name('commission');
    // route contact
    Route::get('contact' , 'StaticPageController@contact')->name('contact');
    // route store contact
    Route::post('store/contact' , 'StaticPageController@store')->name('store.contact');
    // route payment 
    Route::get('payment/{slug}' , 'PaymentController@payment')->name('payment');
    // route web payment now 
    Route::post('payment/now' , 'PaymentController@paymentNow')->name('payment.now');

    ################################################## BEGIN: statics #########################################


    ################################################## BEGIN: active account #########################################
    // route verfiy
    Route::get('verfiy/{slug}' , 'AuthenticationController@verfiy')->name('verfiy');
    // route resend code
    Route::get('resend/code/{slug}' , 'AuthenticationController@resendCode')->name('resend.code');
    // route active phone
    Route::post('active/phone' , 'AuthenticationController@activePhone')->name('active.phone');

    ################################################## END: active account #########################################

    ################################################## BEGIN: reset password #########################################
    // route forget password
    Route::get('forget/password' , 'AuthenticationController@forgetPassword')->name('forget.password');
    // route send code reset password
    Route::post('send/code/reset/password' , 'AuthenticationController@sendCodeResetPassword')->name('send.code.reset.password');
    // route verfiy code reset password
    Route::get('verfiy/code/reset/password/{slug}' , 'AuthenticationController@verfiySendCodeResetPassword')->name('verfiy.code.reset.password');
    // route reset password
    Route::post('active/code/reset/password' , 'AuthenticationController@activeSendCodeResetPassword')->name('active.code.reset.password');
    // route reset password
    Route::get('reset/password/{slug}' , 'AuthenticationController@resetPassword')->name('reset.password');  
    // route reset password
    Route::post('new/password' , 'AuthenticationController@newPassword')->name('new.password');
    
    ################################################## END: reset password #########################################
    

    ################################################## BEGIN: products #########################################
    // route single product
    Route::get('product/{slug}' , 'ProductController@getProduct')->name('product');  
    
    ################################################## END: products ###########################################
    

    ################################################## BEGIN: opposed #########################################
    
    // route opposeds
    Route::get('opposeds' , 'OpposedController@getAllOpposed')->name('opposeds');  
    // route opposed
    Route::get('opposed/{slug}' , 'OpposedController@getOpposed')->name('opposed');  
    
    
    ################################################## END: opposed ###########################################
    
    
    ################################################## BEGIN: opposed #########################################
    
    // route search
    Route::get('public/search' , 'SearchController@searchPublic')->name('public.search');  

    // route search
    Route::post('search' , 'SearchController@searchSimple')->name('search');  
    
    // route search
    Route::get('search/advanced' , 'SearchController@searchAdvanced')->name('search.advanced');  
    
    // route map
    Route::get('search/map' , 'SearchController@searchMap')->name('search.map');  
     
    // route search
    Route::post('search/advanced/store' , 'SearchController@searchAdvancedStore')->name('search.advanced.store'); 

    // route get attribute
    Route::get('get/attribute/search' , 'SearchController@getAttributeSearch')->name('get.attribute.search');

    ################################################## END: opposed ###########################################

    // route get option other addition
    Route::get('get/other/addition' , 'SearchController@getOtherAddition')->name('get.other.addition');


    Route::middleware('website')->group(function(){
        
        // route logout
        Route::get('logout' , 'AuthenticationController@logout')->name('logout');
        // route profile
        Route::get('profile' , 'ProfileController@profile')->name('profile');
        // route edit profile
        Route::get('edit/profile' , 'ProfileController@edit')->name('edit.profile');
        // route update profile
        Route::put('update/profile' , 'ProfileController@update')->name('update.profile');
        // route upload image
        Route::post('upload/image' , 'ProfileController@uploadImage')->name('upload.image');
        // route add to favorite
        Route::get('add/to/favorite' , 'HomeController@addToFavorite')->name('add.to.favorite');
        // route get favorite
        Route::get('profile/favorite' , 'ProfileController@getFavorite')->name('profile.favorite');
        // route my product
        Route::get('profile/product' , 'ProfileController@myProduct')->name('profile.product');
        // route done sale
        Route::get('done/sale' , 'ProfileController@doneSale')->name('done.sale');
        

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Api\Traits\ApiResponseTrait;
use App\Http\Controllers\Controller;
use App\Http\Resources\Api\CategoryResource;
use App\Http\Resources\Api\TypeAuthResource;
use App\Repositories\CategoryRepositoryInterface;
use App\Repositories\TypeAuthRepositoryInterface;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    use ApiResponseTrait;

    public $categoryrepository;
    public $typeauthrepository;

    public function __construct(CategoryRepositoryInterface $categoryrepository,
                                TypeAuthRepositoryInterface $typeauthrepository
    )
    {

        $this->categoryrepository = $categoryrepository;;
        $this->typeauthrepository = $typeauthrepository;;
        
    } // end of construct

    public function category()
    {
        
        $categories = $this->categoryrepository->getWhere(['type' => 'main'] , ['column' => 'id', 'dir' => 'asc']);

        return $this->ApiResponse(CategoryResource::collection($categories) , 'تم' , 200);

    } // end of get categories

    public function subCategory($category)
    {
        
        $subcategories = $this->categoryrepository->getWhere(['parent_id' => $category] , ['column' => 'id', 'dir' => 'asc']);

        if ($subcategories->isNotEmpty()) {

            return $this->ApiResponse(CategoryResource::collection($subcategories) , 'تم' , 200);

        } else 
        {
            return $this->notFoundResponse();
        }

    } // end of get categories    

    public function typeAuth()
    {
        
        $types = $this->typeauthrepository->getWhere(['type' => 1] , ['column' => 'id', 'dir' => 'asc']);

        return $this->ApiResponse(TypeAuthResource::collection($types) , 'تم' , 200);

    } // end of get type auth   
    
    public function additions()
    {

        $additions = $this->categoryrepository->getWhere(['type' => 'adds'] , ['column' => 'id', 'dir' => 'asc']);

        if ($additions->isNotEmpty()) {

            return $this->ApiResponse(CategoryResource::collection($additions) , 'تم' , 200);

        } else 
        {
            return $this->notFoundResponse();
        }
    } // end of additions

    public function additionsother()
    {

        $additions = $this->categoryrepository->getWhere(['type' => 'other_add'] , ['column' => 'id', 'dir' => 'asc']);

        if ($additions->isNotEmpty()) {

            return $this->ApiResponse(CategoryResource::collection($additions) , 'تم' , 200);

        } else 
        {
            return $this->notFoundResponse();
        }
    } // end of additionsother

} // end of class

app/Http/Controllers/Dashboard/AgreementController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AgreementRequest;
use App\Repositories\AgreementRepositoryInterface;
use Illuminate\Http\Request;

class AgreementController extends Controller
{
    public $agreementrepository;

    public function __construct(AgreementRepositoryInterface $agreementrepository)
    {

        $this->agreementrepository = $agreementrepository;
        
    } // end of construct

    public function index()
    {

        $agreements = $this->agreementrepository->getAll();
        
        return view('dashboard.agreements.index' , compact('agreements'));

    } // end of index    

    public function create()
    {

        
        return view('dashboard.agreements.create');

    } // end of create


    public function store(AgreementRequest $request)
    {

        $attribute = $request->except('_token' , '_method');        

        $this->agreementrepository->create($attribute); // end of create
        
        return redirect()->route('dashboard.agreements.index')->with('success' , 'تم اضافة البند بنجاح');

    } // end of update

    public function edit($agreement)
    {
        $agreement_one = $this->agreementrepository->findOne($agreement);

        return view('dashboard.agreements.edit' , compact('agreement_one'));

    } // end of edit

    public function update(AgreementRequest $request , $slider)
    {

        $attribute = $request->except('_token' , '_method');

        $this->agreementrepository->update($attribute , $slider);      

        return redirect()->route('dashboard.agreements.index')->with('success' , 'تم تعديل البند بنجاح');

    } // end of update


    public function destroy($bank)
    {


        $this->agreementrepository->delete($bank);
    
        return response()->json();

        
    } // end of destroy
}

app/Http/Controllers/Dashboard/AttributeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AttributeRequest;
use App\Repositories\AttributeRepositoryInterface;
use App\Repositories\CategoryRepositoryInterface;
use App\Repositories\OptionSubCategoryRepositoryInterface;
use Illuminate\Http\Request;

class AttributeController extends Controller
{
    public $categoryrepository;
    public $attributerepository;

    public function __construct(CategoryRepositoryInterface $categoryrepository,
                                AttributeRepositoryInterface $attributerepository                      
    )
    {

        $this->categoryrepository          = $categoryrepository;
        $this->attributerepository         = $attributerepository;
        
    } // end of construct

    public function index()
    {

        $attributes = $this->attributerepository->attribute();
        
        return view('dashboard.attributes.index' , compact('attributes'));

    } // end of index

    public function create()
    {

        $subcategories = $this->categoryrepository->subcategory();
        $categories = $this->categoryrepository->category();

        return view('dashboard.attributes.create' , compact('subcategories' , 'categories'));

    } // end of create

    public function store(AttributeRequest $request)
    {

        $attribute = $request->except('_token');

        $this->attributerepository->create($attribute);
        
        return redirect()->route('dashboard.attributes.index')->with('success' , 'تم اضافه الخصائص بنجاح');

    } // end of store

    public function edit($attr)
    {
        
        $attribute = $this->attributerepository->findOne($attr);
    
        $categories = $this->categoryrepository->category();

        $subcategories = $this->categoryrepository->getwhere([['parent_id' , $attribute->category_id]]);

        return view('dashboard.attributes.edit' , compact('categories' , 'subcategories' , 'attribute'));
        
    } // end of edit

    public function update(AttributeRequest $request , $attr)
    {

        $attribute = $request->except('_token' , '_method');

        $this->attributerepository->update($attribute , $attr);

        return redirect()->route('dashboard.attributes.index')->with('success' , 'تم تعديل الخصائص بنجاح');

    } // end of update

    public function destroy($attr)
    {

        $this->attributerepository->delete($attr);

        return response()->json();
        
    } // end of destroy


} // end of class

app/Http/Controllers/Web/CategoryController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Repositories\CategoryRepositoryInterface;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    
    public $categoryrepository;

    public function __construct(CategoryRepositoryInterface $categoryrepository)
    {
        $this->categoryrepository = $categoryrepository;
    } // end of construct

    public function category()
    {

        $categories = $this->categoryrepository->getAll();

        return view('website.category' , compact('categories'));

    } // end of category
    
}

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.layout.app')
@section('title', 'اضافة قسم')
@section('content')

    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('dashboard.dashboard') }}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{ route('dashboard.categories.index') }}">انواع السيارات</a>
                                    </li>
                                    <li class="breadcrumb-item active">اضافة
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
               
            </div>
            <div class="content-body">

                <!-- Validation -->
                <section class="bs-validation">
                    <div class="row">
                        <!-- Bootstrap Validation -->
                        <div class="col-md-12 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">انواع السيارات</h4>
                                </div>
                                <div class="card-body">
                                    <form action="{{ route('dashboard.categories.store') }}" method="POST" class="needs-validation" novalidate>
                                        @csrf

                                        <div class="form-group">
                                            <label class="form-label" for="basic-addon-name">النوع </label>
                                            <input type="text" id="basic-addon-name" name="name" value="{{ old('name') }}" class="form-control" placeholder="النوع" aria-label="Name" aria-describedby="basic-addon-name" required />
                                            <div class="">
                                                @if ($errors->has('name'))
                                                    <span class="help-block">
                                                        <strong style="color: red;">{{ $errors->first('name') }}</strong>
                                                    </span>
                                                @endif
                                            </div>                                        
                                        </div>

                                        <div class="row">
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary">اضافة <i data-feather="plus"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- /Bootstrap Validation -->

                    </div>
                </section>
                <!-- /Validation -->

            </div>
        </div>
    </div>
    <!-- END: Content-->
@push('js')
    <script src="{{ url('admin') }}/app-assets/js/forms/categories/create.js"></script>
    <script src="{{ url('admin') }}/app-assets/vendors/js/forms/select/select2.full.min.js"></script>

@endpush

@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.layout.app')
@section('title', 'تعديل قسم')
@section('content')

    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('dashboard.dashboard') }}">الرئيسية</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{ route('dashboard.categories.index') }}">انواع السيارات</a>
                                    </li>
                                    <li class="breadcrumb-item active">تعديل
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
               
            </div>
            <div class="content-body">

                <!-- Validation -->
                <section class="bs-validation">
                    <div class="row">
                        <!-- Bootstrap Validation -->
                        <div class="col-md-12 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">انواع السيارات</h4>
                                </div>
                                <div class="card-body">
                                    <form action="{{ route('dashboard.categories.update' , $subcategory->id) }}" method="POST" class="needs-validation" novalidate>
                                        @method('PUT')
                                        @csrf

                                        <div class="form-group">
                                            <label class="form-label" for="basic-addon-name"> النوع</label>
                                            <input type="text" id="basic-addon-name" name="name" value="{{ $subcategory->name }}" class="form-control" placeholder="اسم القسم" aria-label="Name" aria-describedby="basic-addon-name" required />
                                            <div class="">
                                                @if ($errors->has('name'))
                                                    <span class="help-block">
                                                        <strong style="color: red;">{{ $errors->first('name') }}</strong>
                                                    </span>
                                                @endif
                                            </div>                                          
                                        </div>

                                        <div class="row">
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-primary">تعديل <i data-feather="edit"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- /Bootstrap Validation -->

                    </div>
                </section>
                <!-- /Validation -->

            </div>
        </div>
    </div>
    <!-- END: Content-->
@push('js')
    <script src="{{ url('admin') }}/app-assets/js/forms/categories/create.js"></script>
    <script src="{{ url('admin') }}/app-assets/vendors/js/forms/select/select2.full.min.js"></script>

@endpush

@endsection

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layout.app')
@section('title', 'الاقسام')
@section('content')


    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="breadcrumb-wrapper">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('dashboard.dashboard') }}">الرئيسية</a>
                                    </li>
                                    <!-- <li class="breadcrumb-item"><a href="#">Datatable</a>
                                    </li> -->
                                    <li class="breadcrumb-item active">انواع السيارات
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                    <div class="form-group breadcrumb-right">
                        <div class="dropdown">
                            <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="grid"></i></button>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="{{ route('dashboard.categories.create') }}" title="اضافة نوع جديد"><i class="mr-1" data-feather="plus"></i><span class="align-middle">اضافه نوع جديد</span></a>
                            </div>
                        </div>
                    </div>
                </div>                
            </div>
            <div class="content-body">

                <!-- BEGIN: section -->
                <section id="dashboard-analytics">

                    <!-- List DataTable -->
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <table class="datatables-basic table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>الاسم</th>
                                            <th>الاختيارات</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                        @foreach($subcategories as $subcategory)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $subcategory->name }}</td>
                                            <td>

                                                <a href="{{route('dashboard.categories.edit', $subcategory->id)}}" class="action-edit"><i class="fa fa-edit"></i></a>
                                                <a href="{{route('dashboard.categories.destroy', $subcategory->id)}}" class="action-delete item-delete"><i class="fa fa-trash"></i></a>

                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--/ List DataTable -->

                </section>
                <!-- END: section -->

            </div>
        </div>
    </div>
    <!-- END: Content-->


@endsection